# Generated by Django 3.0.7 on 2020-09-18 14:16

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название место отдыха')),
                ('description_short', models.CharField(blank=True, max_length=200, verbose_name='Короткое описание место отдыха')),
                ('description_long', tinymce.models.HTMLField(blank=True, verbose_name='Полное описание место отдыха')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_order', models.PositiveIntegerField(default=0, verbose_name='Gорядок фотографий')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография место отдыха')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.Place', verbose_name='Cвязь с местом отдыха')),
            ],
            options={
                'ordering': ['photo_order'],
            },
        ),
    ]
